# Generated by Django 4.2.7 on 2023-12-15 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_doctor_account_alter_patient_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Data i godzina wizyty')),
                ('doctor', models.OneToOneField(help_text='Doktor', on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
                ('patient', models.OneToOneField(help_text='Zapisany pacjent', on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
    ]
