# Generated by Django 4.2.7 on 2023-11-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa leku', max_length=150, unique=True)),
                ('needs_rx', models.BooleanField(help_text='Lek na receptę')),
                ('stock', models.IntegerField(help_text='Ilość w magazynie')),
            ],
        ),
        migrations.CreateModel(
            name='Presciption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescribed', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(help_text='Lekarz wystawiający', on_delete=django.db.models.deletion.RESTRICT, to='clinic.doctor')),
                ('patient', models.ForeignKey(help_text='Pacjent', on_delete=django.db.models.deletion.RESTRICT, to='clinic.patient')),
                ('prescription', models.ManyToManyField(help_text='Lista przepisanych leków', to='medicine.medicine')),
            ],
        ),
    ]
