# Generated by Django 4.2.7 on 2023-11-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.CharField(help_text='Opis leku', max_length=200, null=True),
        ),
    ]
